### ISSUE TITLE
Collect information about plugins' support already implemented

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/system-config-dsl-plugin#13]
Some of Praqma people used JAC at their customer or in Praqma and developed scripts to support different plugins. We need to know what and where is implemented - so we can reuse it later

**Comment by ewelinawilkosz2** [comment]
- warnings parser
- git plugin (name & email in global config)
- description setter
- automatic refresh configuration
- email notification
- build publisher
- ssh publisher
- dns configuration

**Comment by ewelinawilkosz2** [comment]
@Andrey9kin is there anything you'd like to add to the list?

**Comment by Andrey9kin** [comment]
@ewelinawilkosz2 everything that I did is already added to the repo
